# Generated by Django 2.2.12 on 2020-06-16 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doabetesite', '0002_marca_marcaproduto_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='nomeImagem',
            field=models.CharField(default='', max_length=200),
        ),
    ]
