# Generated by Django 2.2.12 on 2020-06-16 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doabetesite', '0003_produto_nomeimagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
