# Generated by Django 2.2.12 on 2020-06-16 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doabetesite', '0004_auto_20200615_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(default=' ', max_length=200, unique=True),
        ),
    ]
